version: '3.9'

services:
  db:
    image: postgres:16
    container_name: habit-db
    environment:
      POSTGRES_DB: habit_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kucher05
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: habit-web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/habits
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: habit_tracker
      DB_USER: postgres
      DB_PASSWORD: Kucher05
      DB_PORT: 5432

volumes:
  pg_data:
