# Generated by Django 5.2.9 on 2026-01-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="execution_time",
            field=models.PositiveSmallIntegerField(
                verbose_name="Время выполнения (сек)"
            ),
        ),
    ]
